### ISSUE TITLE
Block mining simulator

### ISSUE THREAD

**Issue by shesek** [yogh-io/bitcoin-yogh-explorer#2]
This used to be available in the block explorer before it was revamped, is it no longer available or am I missing it?

I found this super useful as an educational tool to help people understand how mining works.

**Comment by JornC** [comment]
Ah yes, the revamped version did end up suffering in some of the features. I'll see if I can add something ~similar to the mining simulator in the next few days.

**Comment by shesek** [comment]
That would be amazing, thank you!

**Comment by jlopp** [comment]
I'm getting a 404 when trying to load http://www.yogh.io/mine/ - should this be working?

**Comment by JornC** [comment]
http://yogh.io/mine/ should be working (no www)

**Comment by jlopp** [comment]
Hm, this is pretty odd. It loads fine for me on Chrome, but on Brave the console shows a 404 and brave displays a cached page and says "this page doesn't exist, do you want to check for it on wayback machine" - same thing regardless of if it's the www subdomain or not.

**Comment by JornC** [comment]
Hmm strange. All I can think of is this server does a http -> https redirect, which may be what's causing this. Does this also occur when navigating to https directly?

**Comment by jlopp** [comment]
Yeah, same issue with https://yogh.io/mine/

**Comment by JornC** [comment]
Should work now. Apparently brave does not show the web page's 404, but its own, which was the roundabout way to get the route to work here.

**Comment by jlopp** [comment]
Confirmed fixed.

**Comment by aristarhh2** [comment]
yogh-explorer-client/src/main/java/nl/yogh/wui/component/HorizontalCollapse.java

**Comment by aristarhh2** [comment]
https://yogh.io/mine/

**Comment by shesek** [comment]
Thank you @yogh-io, much appreciated!
