### ISSUE TITLE
Transaction amount is 100x off

### ISSUE THREAD

**Issue by openoms** [yogh-io/bitcoin-yogh-explorer#3]
I was just looking at this txn https://yogh.io/tx/123380f0c3f2beb4cd5285ccfa9b343ef29ca32d52feb9ccce9c4a37ef230954/ and thought it is quite big for a lightning channel.

Turns out yoghi,io shows 100 times more sats than what it is: https://blockstream.info/tx/123380f0c3f2beb4cd5285ccfa9b343ef29ca32d52feb9ccce9c4a37ef230954

Thank you for this beautiful explorer regardless!

**Comment by JornC** [comment]
Oh my, the notorious off-by-one-hundred-x error strikes again! I'll get right on this, thanks for reporting.

**Comment by yogh-io** [comment]
Fixed in 76eb468550a8824f5df34bd3a2443809895821c1
