### ISSUE TITLE
Only first witness stack is displayed in Raw Transaction

### ISSUE THREAD

**Issue by murchandamus** [yogh-io/bitcoin-yogh-explorer#4]
Firstly, thanks for creating this site, I really like using it when trying to explain transaction serialization to people.

I recently noticed that the site seems to show only the first witness stack.

E.g. transaction [3777…35c8](https://yogh.io/tx/37777defed8717c581b4c0509329550e344bdc14ac38f71fc050096887e535c8/), the first transaction with a P2TR keypath spend and a P2TR scriptpath spend has two segwit inputs. The first input has a witness stack with a single witness item and the second witness stack has three witness items

![image](https://user-images.githubusercontent.com/4060799/194409130-aee08171-6082-489e-862f-c447b28815e4.png)

 but only the first witness stack is shown at the bottom:

![image](https://user-images.githubusercontent.com/4060799/194409507-0cec0672-dcf0-4d0c-86b0-e6839261702e.png)

**Comment by JornC** [comment]
Thanks for your issue report and interest in this application!

The serialized transaction interpreter would indeed only try to interpret the witnesses for the first input, the issue has been corrected in https://github.com/yogh-io/bitcoin-yogh-explorer/commit/37904e94:

![image](https://user-images.githubusercontent.com/1552366/194696850-614a80b1-baaa-47c4-a0c2-3e465f4f9946.png)

---

If you have any other issues or feature requests, please let me know and I'd be happy to take a look

**Comment by Xekyo** [comment]
Thank you for the speedy fix and your great application!
